# -*- coding: utf-8 -*-
"""LinearRegressionWGDescent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ySGsVk_aNankSxucJfUMWWTZm1l20tFV
"""

import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv('Google_Stock_Price.csv')

print(df.columns)

X = df[['open', 'high', 'low', 'volume']]
y = df['close']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, random_state=42)

model.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)

print(f"Ortalama Kare Hatası: {mse}")