# -*- coding: utf-8 -*-
"""LinearRegressionWLSE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K901nsZULBBoyVmbtBR1LzQccCSQ9b1o
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('Google_Stock_Price.csv')

X = data['open'].values

y = data['close'].values

X_b = np.c_[np.ones((X.shape[0], 1)), X]
theta_best = np.linalg.solve(X_b.T.dot(X_b), X_b.T.dot(y))

print("Katsayılar:", theta_best)

y_pred = X_b.dot(theta_best)
plt.scatter(X, y, label='Veri')
plt.plot(X, y_pred, color='red', label='Regresyon Doğrusu')
plt.xlabel('Open')
plt.ylabel('Close')
plt.legend()
plt.show()

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y, y_pred)
print("Ortalama Kare Hata:", mse)